### ISSUE TITLE
Based on the Track Player Icon, The map center position is Updated or Not? 

### ISSUE THREAD

**Issue by sditcshj** [argonavt11/leaflet-react-track-player#13]
Each Time based on the Icon movement, I need to drag the map manually. 

Is there any code, to drag the map based on the pointer movement?

**Comment by arg0navt** [comment]
No, but you can use events of the leaflet for it and callbacks of this package

**Comment by sditcshj** [comment]
Can you provide some example code for that?

**Comment by sditcshj** [comment]
Its Fixed
